# Generated by Django 2.2.5 on 2019-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('flat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('views_count', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('floors_amount', models.IntegerField(null=True)),
                ('building_type', models.CharField(max_length=13)),
                ('rooms', models.CharField(max_length=19)),
                ('decoration', models.CharField(max_length=14)),
                ('square', models.FloatField()),
                ('living_square', models.FloatField(null=True)),
                ('kitchen_square', models.FloatField(null=True)),
                ('scraped_date', models.DateTimeField(default=None, null=True)),
                ('finish_date', models.CharField(max_length=18, null=True)),
                ('url', models.URLField()),
                ('district1', models.CharField(default=None, max_length=25, null=True)),
                ('district2', models.CharField(default=None, max_length=25, null=True)),
                ('district3', models.CharField(default=None, max_length=25, null=True)),
                ('region', models.CharField(default=None, max_length=16, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('ip', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
    ]
